apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-consumption-app-deployment
spec:
  selector:
    matchLabels:
      app: energy-consumption-app
  replicas: 3
  template:
    metadata:
      labels:
        app: energy-consumption-app
    spec:
      containers:
        - name: energy-consumption-app
          build: .
          resources:
            limits:
              memory: "200Mi"
            requests:
              memory: "100Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDealySeconds: 5
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
          ports:
            - containerPort: 8080