apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-consumption-mysql-deployment
spec:
  selector:
    matchLabels:
      app: energy-consumption-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: energy-consumption-mysql
    spec:
      containers:
        - name: energy-consumption-mysql
          image: mysql:5.5
          ports:
          - name: mysql
            containerPort: 3306
          resources:
           requests:
            cpu: 500m
            memory: 1Gi
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
