apiVersion: v1
kind: Service
metadata:
  name: energy-consumption-mysql-service
spec:
  selector:
    app: energy-consumption-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306